### 유저 생성
POST http://localhost:4000/user/signup
Content-Type: application/json

{
  "nickname": "Stevenkim",
  "email": "stevenkim@gmail.com",
  "password": "12345678"
}

### 유저 로그인
POST http://localhost:4000/user/login
Content-Type: application/json

{
  "email": "stevenkim@gmail.com",
  "password": "12345678"
}